name: Copy public key and run Ansible playbook

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Ansible
        run: pip install ansible

      - name: Disable host key checking for Ansible
        run: export ANSIBLE_HOST_KEY_CHECKING="False"

      - name: Run Ansible playbook
        run: ansible-playbook -o StrictHostKeyChecking=no -i inventory.ymlplaybook.yml